WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Models/API/Requests/GetLinkRequest.cs
namespace WebDevAcademy.UrlShortener.Models.API.Requests
{
    public class GetLinkRequest
    {
        public int? Page { get; set; } = 1;
        public string Search { get; set; }
    }
}

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Models/API/Requests/ShortenLinkRequest.cs
using WebDevAcademy.UrlShortener.Utils;

namespace WebDevAcademy.UrlShortener.Models.API.Requests
{
    public class ShortenLinkRequest
    {
        public string LongUrl { get; set; }

        public Url GetUrl()
        {
            return UrlShortenerUtil.Shorten(new Url
            {
                LongUrl = this.LongUrl
            });
        }
    }
}

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Models/API/Results/SearchResult.cs
using System.Collections.Generic;

namespace WebDevAcademy.UrlShortener.Models.API.Results
{
    public class SearchResult
    {
        public IEnumerable<LinkResult> Items { get; set; }
        public PageInfo PageInfo { get; set; }
    }

    public class PageInfo
    {
        public int CurrentPage { get; set; }

        public int MaxPage { get; set; }
    }

    public class LinkResult
    {
        public LinkResult(Url url)
        {
            Id = url.Id;
            LongUrl = url.LongUrl;
            ShortUrl = url.ShortUrl;
            UniqueVisits = url.UniqueVisits;
        }

        public int Id { get; set; }
        public string LongUrl { get; set; }
        public string ShortUrl { get; set; }
        public ulong UniqueVisits { get; set; }
    }
}

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Models/ShortenModel.cs
namespace WebDevAcademy.UrlShortener.Models
{
    public class ShortenModel
    {
        public int Id { get; set; }
        public string LongUrl { get; set; }
        public string ShortUrl { get; set; }
    }
}

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Models/Url.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebDevAcademy.UrlShortener.Models
{
    public class Url
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string LongUrl { get; set; }
        public string ShortUrl { get; set; }
        public ulong UniqueVisits { get; set; }
    }
}

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Controllers/LinkApiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Linq;
using WebDevAcademy.UrlShortener.Interfaces;
using WebDevAcademy.UrlShortener.Models;
using WebDevAcademy.UrlShortener.Models.API.Requests;
using WebDevAcademy.UrlShortener.Models.API.Results;

namespace WebDevAcademy.UrlShortener.Controllers
{
    [Route("/api/links")]
    public class LinkApiController : UrlShortenerControllerBase
    {
        private readonly int ITEMS_PER_PAGE;

        public LinkApiController(IUrlRepository repository, IConfiguration configuration) : base(repository)
        {
            ITEMS_PER_PAGE = configuration.GetValue<int>("ApiSettings:ItemsPerPage");
        }

        // GET api/links/{id}
        [HttpGet("{id}")]
        public IActionResult Get(int id)
        {
            var result = _repository.Get(id);

            if (result != null)
                return Ok(result);
            else
                return NotFound($"Could not find item with id = {id}");
        }

        // GET api/links/?search={string}&page={int}
        [HttpGet]
        public IActionResult Get([FromQuery] GetLinkRequest request)
        {
            var (links, count) = _repository.Get(request.Search, (request.Page.Value - 1) * ITEMS_PER_PAGE, ITEMS_PER_PAGE);

            var result = new SearchResult
            {
                PageInfo = new PageInfo
                {
                    CurrentPage = request.Page.Value,
                    MaxPage = count % ITEMS_PER_PAGE == 0 ? count / ITEMS_PER_PAGE : (count / ITEMS_PER_PAGE) + 1
                },
                Items = links.Select(l => new LinkResult(l))
            };
            return Ok(result);
        }

        // POST api/links
        [HttpPost]
        public IActionResult Post([FromBody] ShortenLinkRequest shortenLinkRequest)
            => Ok(_repository.Add(shortenLinkRequest.GetUrl()));

        // DELETE api/links/{id}
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            _repository.Delete(id);
            return Ok();
        }

        // PUT api/links
        [HttpPut]
        public IActionResult Put([FromBody]Url url)
            => Ok(_repository.Update(url));
    }
}

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Controllers/RedirectionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebDevAcademy.UrlShortener.Interfaces;
using WebDevAcademy.UrlShortener.Utils;

namespace WebDevAcademy.UrlShortener.Controllers
{
    [Route("")]
    public class RedirectionController : UrlShortenerControllerBase
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public RedirectionController(IUrlRepository repository, IHttpContextAccessor httpContextAccessor) : base(repository)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet("{hash}")]
        public IActionResult Index(string hash)
        {
            if (string.IsNullOrEmpty(hash))
                return Redirect("Shortener");

            var urlToRedirect = _repository.Get(hash);

            if (urlToRedirect == null)
                return NotFound("Site not found!");

            if (UniqueVisitsCookieUtil.ReadCookie(_httpContextAccessor, urlToRedirect) != "Visited")
            {
                UniqueVisitsCookieUtil.WriteCookie(_httpContextAccessor, urlToRedirect);
                urlToRedirect.UniqueVisits++;
                _repository.Update(urlToRedirect);
            }
            if (urlToRedirect.LongUrl.Contains("http://") || urlToRedirect.LongUrl.Contains("https://"))
                return Redirect(urlToRedirect.LongUrl);
            else
                return Redirect($"http://{urlToRedirect.LongUrl}");
        }
    }
}

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Controllers/ShortenerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using WebDevAcademy.UrlShortener.Interfaces;
using WebDevAcademy.UrlShortener.Models;
using WebDevAcademy.UrlShortener.Utils;

namespace WebDevAcademy.UrlShortener.Controllers
{
    public class ShortenerController : UrlShortenerControllerBase
    {
        public ShortenerController(IUrlRepository repository) : base(repository)
        {
        }

        [HttpGet]
        public IActionResult Index()
            => View(_repository.GetAll());

        [HttpPost]
        public IActionResult Shorten(Url url)
        {
            if (Uri.IsWellFormedUriString(url.LongUrl, UriKind.RelativeOrAbsolute))
            {
                _repository.Add(UrlShortenerUtil.Shorten(url));
                return Redirect("Index");
            }
            return BadRequest("Given URL is not valid");
        }

        [HttpGet]
        public IActionResult Delete(Url url)
        {
            _repository.Delete(url.Id);
            return Redirect("Index");
        }

        [HttpGet]
        public IActionResult Edit(Url url)
        {
            return View(url);
        }

        [HttpPost]
        public IActionResult Update(Url url)
        {
            _repository.Update(url);
            return Redirect("Index");
        }
    }
}

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UrlShortener - Krzysztof Zawadzki</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year.ToString() - Krzysztof Zawadzki</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Views/Shorten/Index.cshtml
@model List<ShortenModel>
@{
    ViewData["Title"] = "Shorten your url";
}
<div class="row">

    @using (Html.BeginForm("ShortenUrl", "Shorten", FormMethod.Post))
    {
        <div class="form-group">
            <input type="text" class="form-control" name="LongUrl" placeholder="Place your url here..." /><br />
            <button type="submit" class="btn btn-primary">Shorten!</button>
        </div>
    }
</div>

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Views/Shortener/Edit.cshtml
@model Url
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<div class="row">
    @using (Html.BeginForm("Update", "Shortener", FormMethod.Post))
    {
        <div class="form-group">
            <input type="text" class="form-control" name="LongUrl" value="@Model.LongUrl" /> <br />
            <input type="text" class="form-control" name="ShortUrl" value="@Model.ShortUrl" readonly="readonly" /> <br />
            @Html.HiddenFor(model => Model.Id)
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    }
</div>

WebDevAcademy.UrlShortener/WebDevAcademy.UrlShortener/Views/Shortener/Index.cshtml
@model List<Url>
@{
    ViewData["Title"] = "Shorten your url";
}
<div class="row">

    @using (Html.BeginForm("Shorten", "Shortener", FormMethod.Post))
    {
        <div class="form-group">
            <input type="text" class="form-control" name="LongUrl" placeholder="Place your url here..." /><br />
            <button type="submit" class="btn btn-primary">Shorten!</button>
        </div>
    }
</div>

<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Long url</th>
                <th scope="col">Short url</th>
                <th scope="col">Unique visits</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(model => item.LongUrl)</td>
                <td>@Html.ActionLink(item.ShortUrl, "Index", "Redirection", new { hash = item.ShortUrl }, new { target = "_blank"})</td>
                <td>@Html.DisplayFor(model => item.UniqueVisits)</td>
                <td>@Html.ActionLink("Edit", "Edit", "Shortener", item)</td>
                <td>@Html.ActionLink("Delete", "Delete", "Shortener", item)</td>
            </tr>
            }
        </tbody>
    </table>
</div>